// Generated by gencpp from file tensor_rt/MessagesRequest.msg
// DO NOT EDIT!


#ifndef TENSOR_RT_MESSAGE_MESSAGESREQUEST_H
#define TENSOR_RT_MESSAGE_MESSAGESREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace tensor_rt
{
template <class ContainerAllocator>
struct MessagesRequest_
{
  typedef MessagesRequest_<ContainerAllocator> Type;

  MessagesRequest_()
    : object(0)  {
    }
  MessagesRequest_(const ContainerAllocator& _alloc)
    : object(0)  {
  (void)_alloc;
    }



   typedef int32_t _object_type;
  _object_type object;





  typedef boost::shared_ptr< ::tensor_rt::MessagesRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::tensor_rt::MessagesRequest_<ContainerAllocator> const> ConstPtr;

}; // struct MessagesRequest_

typedef ::tensor_rt::MessagesRequest_<std::allocator<void> > MessagesRequest;

typedef boost::shared_ptr< ::tensor_rt::MessagesRequest > MessagesRequestPtr;
typedef boost::shared_ptr< ::tensor_rt::MessagesRequest const> MessagesRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::tensor_rt::MessagesRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::tensor_rt::MessagesRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::tensor_rt::MessagesRequest_<ContainerAllocator1> & lhs, const ::tensor_rt::MessagesRequest_<ContainerAllocator2> & rhs)
{
  return lhs.object == rhs.object;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::tensor_rt::MessagesRequest_<ContainerAllocator1> & lhs, const ::tensor_rt::MessagesRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace tensor_rt

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::tensor_rt::MessagesRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tensor_rt::MessagesRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tensor_rt::MessagesRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tensor_rt::MessagesRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tensor_rt::MessagesRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tensor_rt::MessagesRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::tensor_rt::MessagesRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "697f5f1b63c5a2c12b7d7f348a45ff41";
  }

  static const char* value(const ::tensor_rt::MessagesRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x697f5f1b63c5a2c1ULL;
  static const uint64_t static_value2 = 0x2b7d7f348a45ff41ULL;
};

template<class ContainerAllocator>
struct DataType< ::tensor_rt::MessagesRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "tensor_rt/MessagesRequest";
  }

  static const char* value(const ::tensor_rt::MessagesRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::tensor_rt::MessagesRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 object\n"
"\n"
;
  }

  static const char* value(const ::tensor_rt::MessagesRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::tensor_rt::MessagesRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.object);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MessagesRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::tensor_rt::MessagesRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::tensor_rt::MessagesRequest_<ContainerAllocator>& v)
  {
    s << indent << "object: ";
    Printer<int32_t>::stream(s, indent + "  ", v.object);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TENSOR_RT_MESSAGE_MESSAGESREQUEST_H
