// Generated by gencpp from file tensor_rt/MessagesResponse.msg
// DO NOT EDIT!


#ifndef TENSOR_RT_MESSAGE_MESSAGESRESPONSE_H
#define TENSOR_RT_MESSAGE_MESSAGESRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace tensor_rt
{
template <class ContainerAllocator>
struct MessagesResponse_
{
  typedef MessagesResponse_<ContainerAllocator> Type;

  MessagesResponse_()
    : result()  {
    }
  MessagesResponse_(const ContainerAllocator& _alloc)
    : result(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<int32_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<int32_t>> _result_type;
  _result_type result;





  typedef boost::shared_ptr< ::tensor_rt::MessagesResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::tensor_rt::MessagesResponse_<ContainerAllocator> const> ConstPtr;

}; // struct MessagesResponse_

typedef ::tensor_rt::MessagesResponse_<std::allocator<void> > MessagesResponse;

typedef boost::shared_ptr< ::tensor_rt::MessagesResponse > MessagesResponsePtr;
typedef boost::shared_ptr< ::tensor_rt::MessagesResponse const> MessagesResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::tensor_rt::MessagesResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::tensor_rt::MessagesResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::tensor_rt::MessagesResponse_<ContainerAllocator1> & lhs, const ::tensor_rt::MessagesResponse_<ContainerAllocator2> & rhs)
{
  return lhs.result == rhs.result;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::tensor_rt::MessagesResponse_<ContainerAllocator1> & lhs, const ::tensor_rt::MessagesResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace tensor_rt

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::tensor_rt::MessagesResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tensor_rt::MessagesResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tensor_rt::MessagesResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tensor_rt::MessagesResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tensor_rt::MessagesResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tensor_rt::MessagesResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::tensor_rt::MessagesResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "735d5bb657ca4356bf24ff5eb86bf466";
  }

  static const char* value(const ::tensor_rt::MessagesResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x735d5bb657ca4356ULL;
  static const uint64_t static_value2 = 0xbf24ff5eb86bf466ULL;
};

template<class ContainerAllocator>
struct DataType< ::tensor_rt::MessagesResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "tensor_rt/MessagesResponse";
  }

  static const char* value(const ::tensor_rt::MessagesResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::tensor_rt::MessagesResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32[] result\n"
;
  }

  static const char* value(const ::tensor_rt::MessagesResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::tensor_rt::MessagesResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.result);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MessagesResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::tensor_rt::MessagesResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::tensor_rt::MessagesResponse_<ContainerAllocator>& v)
  {
    s << indent << "result[]" << std::endl;
    for (size_t i = 0; i < v.result.size(); ++i)
    {
      s << indent << "  result[" << i << "]: ";
      Printer<int32_t>::stream(s, indent + "  ", v.result[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // TENSOR_RT_MESSAGE_MESSAGESRESPONSE_H
