// Generated by gencpp from file tensor_rt/Messages.msg
// DO NOT EDIT!


#ifndef TENSOR_RT_MESSAGE_MESSAGES_H
#define TENSOR_RT_MESSAGE_MESSAGES_H

#include <ros/service_traits.h>


#include <tensor_rt/MessagesRequest.h>
#include <tensor_rt/MessagesResponse.h>


namespace tensor_rt
{

struct Messages
{

typedef MessagesRequest Request;
typedef MessagesResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Messages
} // namespace tensor_rt


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::tensor_rt::Messages > {
  static const char* value()
  {
    return "bdb4ecf8e91e5c89bb2f7e7af5cf8ea3";
  }

  static const char* value(const ::tensor_rt::Messages&) { return value(); }
};

template<>
struct DataType< ::tensor_rt::Messages > {
  static const char* value()
  {
    return "tensor_rt/Messages";
  }

  static const char* value(const ::tensor_rt::Messages&) { return value(); }
};


// service_traits::MD5Sum< ::tensor_rt::MessagesRequest> should match
// service_traits::MD5Sum< ::tensor_rt::Messages >
template<>
struct MD5Sum< ::tensor_rt::MessagesRequest>
{
  static const char* value()
  {
    return MD5Sum< ::tensor_rt::Messages >::value();
  }
  static const char* value(const ::tensor_rt::MessagesRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::tensor_rt::MessagesRequest> should match
// service_traits::DataType< ::tensor_rt::Messages >
template<>
struct DataType< ::tensor_rt::MessagesRequest>
{
  static const char* value()
  {
    return DataType< ::tensor_rt::Messages >::value();
  }
  static const char* value(const ::tensor_rt::MessagesRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::tensor_rt::MessagesResponse> should match
// service_traits::MD5Sum< ::tensor_rt::Messages >
template<>
struct MD5Sum< ::tensor_rt::MessagesResponse>
{
  static const char* value()
  {
    return MD5Sum< ::tensor_rt::Messages >::value();
  }
  static const char* value(const ::tensor_rt::MessagesResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::tensor_rt::MessagesResponse> should match
// service_traits::DataType< ::tensor_rt::Messages >
template<>
struct DataType< ::tensor_rt::MessagesResponse>
{
  static const char* value()
  {
    return DataType< ::tensor_rt::Messages >::value();
  }
  static const char* value(const ::tensor_rt::MessagesResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TENSOR_RT_MESSAGE_MESSAGES_H
