// Generated by gencpp from file tensor_rt/msg_1.msg
// DO NOT EDIT!


#ifndef TENSOR_RT_MESSAGE_MSG_1_H
#define TENSOR_RT_MESSAGE_MSG_1_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace tensor_rt
{
template <class ContainerAllocator>
struct msg_1_
{
  typedef msg_1_<ContainerAllocator> Type;

  msg_1_()
    : target_class(0)  {
    }
  msg_1_(const ContainerAllocator& _alloc)
    : target_class(0)  {
  (void)_alloc;
    }



   typedef uint16_t _target_class_type;
  _target_class_type target_class;





  typedef boost::shared_ptr< ::tensor_rt::msg_1_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::tensor_rt::msg_1_<ContainerAllocator> const> ConstPtr;

}; // struct msg_1_

typedef ::tensor_rt::msg_1_<std::allocator<void> > msg_1;

typedef boost::shared_ptr< ::tensor_rt::msg_1 > msg_1Ptr;
typedef boost::shared_ptr< ::tensor_rt::msg_1 const> msg_1ConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::tensor_rt::msg_1_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::tensor_rt::msg_1_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::tensor_rt::msg_1_<ContainerAllocator1> & lhs, const ::tensor_rt::msg_1_<ContainerAllocator2> & rhs)
{
  return lhs.target_class == rhs.target_class;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::tensor_rt::msg_1_<ContainerAllocator1> & lhs, const ::tensor_rt::msg_1_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace tensor_rt

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::tensor_rt::msg_1_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tensor_rt::msg_1_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tensor_rt::msg_1_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tensor_rt::msg_1_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tensor_rt::msg_1_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tensor_rt::msg_1_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::tensor_rt::msg_1_<ContainerAllocator> >
{
  static const char* value()
  {
    return "997878a101ab058a18257fccc8baf249";
  }

  static const char* value(const ::tensor_rt::msg_1_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x997878a101ab058aULL;
  static const uint64_t static_value2 = 0x18257fccc8baf249ULL;
};

template<class ContainerAllocator>
struct DataType< ::tensor_rt::msg_1_<ContainerAllocator> >
{
  static const char* value()
  {
    return "tensor_rt/msg_1";
  }

  static const char* value(const ::tensor_rt::msg_1_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::tensor_rt::msg_1_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint16 target_class\n"
;
  }

  static const char* value(const ::tensor_rt::msg_1_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::tensor_rt::msg_1_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.target_class);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct msg_1_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::tensor_rt::msg_1_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::tensor_rt::msg_1_<ContainerAllocator>& v)
  {
    s << indent << "target_class: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.target_class);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TENSOR_RT_MESSAGE_MSG_1_H
