// Generated by gencpp from file tensor_rt/msg_2.msg
// DO NOT EDIT!


#ifndef TENSOR_RT_MESSAGE_MSG_2_H
#define TENSOR_RT_MESSAGE_MSG_2_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace tensor_rt
{
template <class ContainerAllocator>
struct msg_2_
{
  typedef msg_2_<ContainerAllocator> Type;

  msg_2_()
    : room(0)
    , detected_class(0)  {
    }
  msg_2_(const ContainerAllocator& _alloc)
    : room(0)
    , detected_class(0)  {
  (void)_alloc;
    }



   typedef int32_t _room_type;
  _room_type room;

   typedef int32_t _detected_class_type;
  _detected_class_type detected_class;





  typedef boost::shared_ptr< ::tensor_rt::msg_2_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::tensor_rt::msg_2_<ContainerAllocator> const> ConstPtr;

}; // struct msg_2_

typedef ::tensor_rt::msg_2_<std::allocator<void> > msg_2;

typedef boost::shared_ptr< ::tensor_rt::msg_2 > msg_2Ptr;
typedef boost::shared_ptr< ::tensor_rt::msg_2 const> msg_2ConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::tensor_rt::msg_2_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::tensor_rt::msg_2_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::tensor_rt::msg_2_<ContainerAllocator1> & lhs, const ::tensor_rt::msg_2_<ContainerAllocator2> & rhs)
{
  return lhs.room == rhs.room &&
    lhs.detected_class == rhs.detected_class;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::tensor_rt::msg_2_<ContainerAllocator1> & lhs, const ::tensor_rt::msg_2_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace tensor_rt

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::tensor_rt::msg_2_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tensor_rt::msg_2_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tensor_rt::msg_2_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tensor_rt::msg_2_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tensor_rt::msg_2_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tensor_rt::msg_2_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::tensor_rt::msg_2_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d4962e33f389591ae16435b9eda70efd";
  }

  static const char* value(const ::tensor_rt::msg_2_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd4962e33f389591aULL;
  static const uint64_t static_value2 = 0xe16435b9eda70efdULL;
};

template<class ContainerAllocator>
struct DataType< ::tensor_rt::msg_2_<ContainerAllocator> >
{
  static const char* value()
  {
    return "tensor_rt/msg_2";
  }

  static const char* value(const ::tensor_rt::msg_2_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::tensor_rt::msg_2_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 room\n"
"int32 detected_class\n"
;
  }

  static const char* value(const ::tensor_rt::msg_2_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::tensor_rt::msg_2_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.room);
      stream.next(m.detected_class);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct msg_2_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::tensor_rt::msg_2_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::tensor_rt::msg_2_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "room: ";
    Printer<int32_t>::stream(s, indent + "  ", v.room);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "detected_class: ";
    Printer<int32_t>::stream(s, indent + "  ", v.detected_class);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TENSOR_RT_MESSAGE_MSG_2_H
