// Generated by gencpp from file tensor_rt/SimCarCommResponse.msg
// DO NOT EDIT!


#ifndef TENSOR_RT_MESSAGE_SIMCARCOMMRESPONSE_H
#define TENSOR_RT_MESSAGE_SIMCARCOMMRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace tensor_rt
{
template <class ContainerAllocator>
struct SimCarCommResponse_
{
  typedef SimCarCommResponse_<ContainerAllocator> Type;

  SimCarCommResponse_()
    : target_class(0)  {
    }
  SimCarCommResponse_(const ContainerAllocator& _alloc)
    : target_class(0)  {
  (void)_alloc;
    }



   typedef int32_t _target_class_type;
  _target_class_type target_class;





  typedef boost::shared_ptr< ::tensor_rt::SimCarCommResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::tensor_rt::SimCarCommResponse_<ContainerAllocator> const> ConstPtr;

}; // struct SimCarCommResponse_

typedef ::tensor_rt::SimCarCommResponse_<std::allocator<void> > SimCarCommResponse;

typedef boost::shared_ptr< ::tensor_rt::SimCarCommResponse > SimCarCommResponsePtr;
typedef boost::shared_ptr< ::tensor_rt::SimCarCommResponse const> SimCarCommResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::tensor_rt::SimCarCommResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::tensor_rt::SimCarCommResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::tensor_rt::SimCarCommResponse_<ContainerAllocator1> & lhs, const ::tensor_rt::SimCarCommResponse_<ContainerAllocator2> & rhs)
{
  return lhs.target_class == rhs.target_class;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::tensor_rt::SimCarCommResponse_<ContainerAllocator1> & lhs, const ::tensor_rt::SimCarCommResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace tensor_rt

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::tensor_rt::SimCarCommResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tensor_rt::SimCarCommResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tensor_rt::SimCarCommResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tensor_rt::SimCarCommResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tensor_rt::SimCarCommResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tensor_rt::SimCarCommResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::tensor_rt::SimCarCommResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e88f1a029f311d014085879de9fb23af";
  }

  static const char* value(const ::tensor_rt::SimCarCommResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe88f1a029f311d01ULL;
  static const uint64_t static_value2 = 0x4085879de9fb23afULL;
};

template<class ContainerAllocator>
struct DataType< ::tensor_rt::SimCarCommResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "tensor_rt/SimCarCommResponse";
  }

  static const char* value(const ::tensor_rt::SimCarCommResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::tensor_rt::SimCarCommResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 target_class  #实际环境中的目标类别\n"
;
  }

  static const char* value(const ::tensor_rt::SimCarCommResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::tensor_rt::SimCarCommResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.target_class);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SimCarCommResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::tensor_rt::SimCarCommResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::tensor_rt::SimCarCommResponse_<ContainerAllocator>& v)
  {
    s << indent << "target_class: ";
    Printer<int32_t>::stream(s, indent + "  ", v.target_class);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TENSOR_RT_MESSAGE_SIMCARCOMMRESPONSE_H
