// Generated by gencpp from file tensor_rt/SimCarComm.msg
// DO NOT EDIT!


#ifndef TENSOR_RT_MESSAGE_SIMCARCOMM_H
#define TENSOR_RT_MESSAGE_SIMCARCOMM_H

#include <ros/service_traits.h>


#include <tensor_rt/SimCarCommRequest.h>
#include <tensor_rt/SimCarCommResponse.h>


namespace tensor_rt
{

struct SimCarComm
{

typedef SimCarCommRequest Request;
typedef SimCarCommResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SimCarComm
} // namespace tensor_rt


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::tensor_rt::SimCarComm > {
  static const char* value()
  {
    return "932cc26da5c945312b522ef7ce57d5c8";
  }

  static const char* value(const ::tensor_rt::SimCarComm&) { return value(); }
};

template<>
struct DataType< ::tensor_rt::SimCarComm > {
  static const char* value()
  {
    return "tensor_rt/SimCarComm";
  }

  static const char* value(const ::tensor_rt::SimCarComm&) { return value(); }
};


// service_traits::MD5Sum< ::tensor_rt::SimCarCommRequest> should match
// service_traits::MD5Sum< ::tensor_rt::SimCarComm >
template<>
struct MD5Sum< ::tensor_rt::SimCarCommRequest>
{
  static const char* value()
  {
    return MD5Sum< ::tensor_rt::SimCarComm >::value();
  }
  static const char* value(const ::tensor_rt::SimCarCommRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::tensor_rt::SimCarCommRequest> should match
// service_traits::DataType< ::tensor_rt::SimCarComm >
template<>
struct DataType< ::tensor_rt::SimCarCommRequest>
{
  static const char* value()
  {
    return DataType< ::tensor_rt::SimCarComm >::value();
  }
  static const char* value(const ::tensor_rt::SimCarCommRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::tensor_rt::SimCarCommResponse> should match
// service_traits::MD5Sum< ::tensor_rt::SimCarComm >
template<>
struct MD5Sum< ::tensor_rt::SimCarCommResponse>
{
  static const char* value()
  {
    return MD5Sum< ::tensor_rt::SimCarComm >::value();
  }
  static const char* value(const ::tensor_rt::SimCarCommResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::tensor_rt::SimCarCommResponse> should match
// service_traits::DataType< ::tensor_rt::SimCarComm >
template<>
struct DataType< ::tensor_rt::SimCarCommResponse>
{
  static const char* value()
  {
    return DataType< ::tensor_rt::SimCarComm >::value();
  }
  static const char* value(const ::tensor_rt::SimCarCommResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TENSOR_RT_MESSAGE_SIMCARCOMM_H
