#Description:
#  本地代价地图需要配置的参数，各参数意义如下:
#  global_frame:在本地代价地图中的全局坐标系;
#  robot_base_frame:机器人本体的基坐标系;

local_costmap:
  global_frame: map
  robot_base_frame: base_link
  update_frequency: 6.0
  publish_frequency: 6.0
  static_map: false
  rolling_window: true
  width: 3.5
  height: 3.0
  resolution: 0.04

  cost_scaling_factor: 16   #22
  inflation_radius: 0.38          #0.75


  transform_tolerance: 2
  plugins:
#    - {name: static_layer,    type: "costmap_2d::StaticLayer"}
    - {name: obstacle_layer,  type: "costmap_2d::ObstacleLayer"}
    - {name: inflation_layer, type: "costmap_2d::InflationLayer"}
