DWAPlannerROS:


# Robot Configuration Parameters
  # 加速度限速
  acc_lim_x: 0.1
  acc_lim_y: 0.0
  acc_lim_th: 1000
  # robot平移速度限速
  max_vel_trans:  0.3
  min_vel_trans:  0.11
  # x,y轴方向线速度限速
  max_vel_x: 0.3
  min_vel_x: -0.3
  max_vel_y: 0.0
  min_vel_y: 0.0
  # 旋转角速度限速
  max_vel_theta: 0.4
  min_vel_theta: 0.157


# Goal Tolerance Parametes
  # 到达目标点时偏行角允许的误差
  yaw_goal_tolerance: 0.17
  # 到达目标点时距离允许的误差
  xy_goal_tolerance: 0.05
  # 设置为true时表示：如果到达容错距离内,机器人就会原地旋转；即使转动是会跑出容错距离外
  latch_xy_goal_tolerance: true


# Forward Simulation Parameters
  # 前向模拟轨迹的时间
  sim_time: 1.5
  # xy方向速度空间的采样点数.
  vx_samples: 20
  vy_samples: 0
  #旋转方向的速度空间采样点数
  vth_samples: 40
  #控制周期和发布速度指令的频率/HZ，moc_base里有设置过
  controller_frequency: 10.0


# Trajectory Scoring Parameters
  #控制器与给定路径接近程度的权重
  path_distance_bias: 32.0
  #控制器与局部目标点的接近程度的权重，也用于速度控制
  goal_distance_bias: 0.9
  #控制器躲避障碍物的程度
  occdist_scale: 0.05
  #以机器人为中心，额外放置一个计分点的距离
  forward_point_distance: 0.325
  #为防止碰撞,机器人必须提前停止的时间长度
  stop_time_buffer: 0.02
  #启动机器人底盘的速度
  scaling_speed: 0.25
  #最大缩放因子
  max_scaling_factor: 0.2


# Oscillation Prevention Parameters
  #机器人运动多远距离才会重置振荡标记
  oscillation_reset_dist: 0.05


# Global Plan Parameters
  #如果设置为true，则当机器人移动1米经过目标点时，目标点将从plan中移除
  prune_plan: true


# Debugging
  #将规划的轨迹在RVIZ上进行可视化
  publish_traj_pc: true
  #将代价值进行可视化显示
  publish_cost_grid_pc: true







