#是否关闭costmaps节点
shutdown_costmaps: false
#控制周期和发布速度指令的频率/HZ
controller_frequency: 20.0
#等待规划的最长时间
planner_patience: 5.0
#等待指令的最长时间
controller_patience: 15.0
#障碍物距离
conservative_reset_dist: 2.0
#global planning运行频率
planner_frequency: 10.0
#recovery恢复行为恢复等待超时时间
oscillation_timeout: 100.0
#recovery恢复有效移动距离
oscillation_distance: 0.01

